default:
  before_script:
    - 'apk update'
    - 'apk upgrade'
    - 'apk add nodejs-current npm'
    - 'npm install --global yarn'

  image: 'alpine:latest'

lint:
  script:
    - 'apk add git shellcheck yamllint'
    - 'yarn install --frozen-lockfile'

    - 'yarn lint'

  stage: 'lint'

release:
  artifacts:
    expire_in: 'never'
    paths:
      - 'dist/snapraid-btrfs-wrapper-${CI_COMMIT_TAG}.tar.xz'

  only:
    - 'tags'

  script:
    - 'apk add curl xz'

    - yarn release-ci

  stage: 'release'

stages:
  - 'lint'
  - 'test'
  - 'release'

test:
  script:
    - 'apk add bash'
    - 'yarn test'

  stage: 'test'
