image: 'alpine:latest'

lint:
  script:
    - 'apk update'
    - 'apk upgrade'

    - 'apk add make nodejs-current npm shellcheck yamllint'

    - 'npm install --global yarn'

    - 'make deps'

    - 'make lint'
