jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'

      - name: 'Setup node'
        uses: 'actions/setup-node@v2-beta'

      - id: 'release-ci'
        name: 'Run CI release script'
        run: 'yarn release-ci'

      - env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        id: 'create-release'
        name: 'Create release'
        uses: 'actions/create-release@v1'
        with:
          body: '${{ steps.release-ci.outputs.changelog }}'
          release_name: 'snapraid-btrfs-wrapper ${{ github.ref }}'
          tag_name: '${{ github.ref }}'

      - env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        name: 'Upload release archive'
        uses: 'actions/upload-release-asset@v1'
        with:
          asset_content_type: 'application/octet-stream'
          asset_name: '${{ steps.release-ci.outputs.filename }}'
          asset_path: '${{ steps.release-ci.outputs.filepath }}'
          upload_url: '${{ steps.create-release.outputs.upload_url }}'
    timeout-minutes: 10

name: 'Release'

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'
